apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service
spec:
  # This selector must match the label on your Nginx Pod
  selector:
    app: nginx
  type: NodePort # This is the key: it opens a port on the VM host
  ports:
    - protocol: TCP
      port: 8080         # The internal service port
      targetPort: 80   # The port Nginx is listening on inside the container (default is 80)
      nodePort: 31111